// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfzw2xD98ojf68rnrrDAi2Lq5W2LqDYEw',
    appId: '1:110419393356:web:5cbacf57dca4aa54de2de9',
    messagingSenderId: '110419393356',
    projectId: 'chatappflutter-99ba7',
    authDomain: 'chatappflutter-99ba7.firebaseapp.com',
    storageBucket: 'chatappflutter-99ba7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4u1DyPErylJAFEcaqJt-LKIixGVFy5vw',
    appId: '1:110419393356:android:cd3f530750f1bd28de2de9',
    messagingSenderId: '110419393356',
    projectId: 'chatappflutter-99ba7',
    storageBucket: 'chatappflutter-99ba7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Vgelicw_vuAGzR0f1ugy43I0DZ8I2BQ',
    appId: '1:110419393356:ios:51dfe85a3a7119c0de2de9',
    messagingSenderId: '110419393356',
    projectId: 'chatappflutter-99ba7',
    storageBucket: 'chatappflutter-99ba7.appspot.com',
    iosBundleId: 'com.example.ladr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Vgelicw_vuAGzR0f1ugy43I0DZ8I2BQ',
    appId: '1:110419393356:ios:4f02ce078b52a1adde2de9',
    messagingSenderId: '110419393356',
    projectId: 'chatappflutter-99ba7',
    storageBucket: 'chatappflutter-99ba7.appspot.com',
    iosBundleId: 'com.example.ladr.RunnerTests',
  );
}
